# NumPy

In [2]:
import numpy as np

In [2]:
L1 = [1,2,3,4,5,6,7,8]# Crear una lista

In [3]:
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x2 = np.array(L1, dtype='float32')
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16, float32, float64 (+/-999.9999999e99999)
- complex_, complex64, complex128 (a+bi, a,b $\in$ float_) 

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3,12,dtype=np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [10]:
np.linspace(1., 7., 12) # 12 valores entre 1 y 7

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [11]:
np.eye(5) # Matriz identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

In [15]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
x.reshape((6,4)) # Redistribuir los elementos

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
x.reshape((3,8)) # La redimencion debe ser posible en tamaño

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

In [18]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.ravel(x) # Aplanar el vector original

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x.flatten() # Copia aplanada del vector

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.transpose(x) # Transponer

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
np.resize(x, (5, 3)) # Redimenciona, si es mas grande que el original rellena con valores repetidos

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios
1. Crear un array de datos con valores entre 5 y 120.
2. Crear una matriz 4x4 con los valores desde 0 hasta 15.
3. Crear la identidad 7x7
4. Crear un array de 20 elementos y transformarlos en una matrix 5x4
5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme

## Propiedades de los arrays

In [27]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
x.ndim # Dimensiones de la matriz

2

In [30]:
x.shape # Filas, Columnas

(3, 4)

In [31]:
x.size # Cantidad de valores

12

In [32]:
x.dtype # Tipo de dato

dtype('int64')

In [33]:
x.itemsize # Tamaño en bytes de cada elemento de la matriz

8

In [34]:
x.data # Buffer que contiene a los elementos de la matriz

In [35]:
x[2] # Acceder a la fila 2, contando desde 0

array([ 8,  9, 10, 11])

In [36]:
x[2,1] # Valor en fil 2, col 1

9

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#### Submatrices

In [37]:
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
x[1:3, 0:2] # Submatriz

array([[3, 4],
       [6, 7]])

In [39]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
y[3:8]

array([3, 4, 5, 6, 7])

In [41]:
y[1:7:2]

array([1, 3, 5])

In [42]:
z = np.arange(10, 6, -1)
z

array([10,  9,  8,  7])

In [43]:
y[z] # Los valores de y en posiciones Z

array([10,  9,  8,  7])

In [44]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [47]:
cond = (x < 25) # Generar un vector logico
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [48]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
x[13:16] = [6,9,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
x.dtype

dtype('int64')

In [52]:
x[5] = 3.1415
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
x[8] = 1.2j 

TypeError: can't convert complex to int

## Copias y vistas de arrays

In [3]:
x = np.arange(10)

In [4]:
y = x

In [5]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
z is x

False

In [60]:
y is x

True

In [8]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
t = x.view() # t es un vista de x
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
t.shape = (5,2) # redimenciono t sin modificar a x
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
s = x[0:2, 1:3] # Esto es una vista
s

array([[1, 2],
       [6, 7]])

In [66]:
s[:] = 5 # Si modifico los valores de una vista tambien estoy modificando la matriz original
s

array([[5, 5],
       [5, 5]])

In [67]:
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [68]:
y # y = x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [69]:
z # z = x.copy()

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Funciones Univeresales (ufunc)
- Unarias(elemento a elemento): sqrt, sin, cos, **2    
- Binarias(reciben dos arrays y devuelven un unico array como resultado usualmente): maximum, minimum    

In [70]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [73]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [74]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

___

In [14]:
alpha = np.linspace(0,2*np.pi, 4) # 4 angulos entre 0 y 2 pi
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [76]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [77]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [78]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

___

In [79]:
np.exp(x) # e elevado a cada elemento del vector

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [80]:
np.exp2(x) # 2 elevado a cada elemento del vector

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [81]:
np.power(3,x) # 3 elevado a cada elemento del vector

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [82]:
np.power(x, 2) # cada elemento elevado a 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

___

In [83]:
np.log(x)

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [84]:
np.log2(x)

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [85]:
np.log10(x)

/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

___

#### Funciones estadisticas, de cada una de estas existe una version para trabajar con valores nan

In [86]:
np.sum(x) # Sumatoria 

45

In [87]:
np.nansum(x)

45

$$\sum_{i=1}^n x_i$$

In [88]:
np.prod(x) # Producto de los elementos

0

In [89]:
np.mean(x) # media de los elementos

4.5

In [90]:
np.median(x) # mediana de los elementos

4.5

In [91]:
np.min(x) # minimo

0

In [92]:
np.max(x) # maximo

9

In [93]:
np.std(x) # Desviasion tipica

2.8722813232690143

In [94]:
np.var(x) # Varianza

8.25

In [95]:
np.argmin(x) # Posicion del valor mas pequeño

0

In [96]:
np.argmax(x) # Posicion del valor mas grande

9

In [99]:
np.percentile(x, q=0.95) # calculo del percentil

0.08549999999999999

___

In [105]:
 y = np.array([True, True, True, True])

In [106]:
np.any(y) # Si algun elemento posee True 

True

In [107]:
np.all(y) # Si todos los elementos poseen True

True

___

In [116]:
np.random.seed(2019) # Semilla
z = np.random.random((3,5)) # Valores aleatoreos
z

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])

In [117]:
z.sum()

8.550690063213514

In [118]:
z.sum(axis=0) # Suma por columnas

array([1.65510085, 1.3623491 , 1.69004099, 2.40847402, 1.43472509])

In [119]:
z.sum(axis=1) # suma por filas

array([3.43890915, 3.19170818, 1.92007274])

## Un poco de algebra lineal en Python

In [20]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]]) #, dtype = complex) Matriz de complejos
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
M.dot(M) # Producto de matrices

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [22]:
M.trace() # Traza de la matriz

15

In [ ]:
np.linalg. # Paquete de algebra lineal

In [27]:
np.linalg.matrix_rank(M)

2

In [36]:
X = np.array([[1,2],[0,1]])

In [39]:
np.linalg.det(X) # Distinta a 0, inversible

1.0

In [37]:
Y = np.linalg.inv(X) # Inversa de la matriz
Y

array([[ 1., -2.],
       [ 0.,  1.]])

In [38]:
Y.dot(X)

array([[1., 0.],
       [0., 1.]])

In [40]:
np.linalg.det(M) # Muy cercana a 0, no inversible. Si la calculo llego a algo pero no es correcta

6.66133814775094e-16

##### No se nos ocurrira nunca hacer la inversa ni de una matriz no cuadrada, ni de una matriz cuyo rango sea inferior a us orden (el numero de filas / columnas de la misma)